name: cito
channels:
  - aahendriksen
  - nvidia
  - astra-toolbox
  - defaults
  - conda-forge
dependencies:
  - astra-toolbox=2.2.0
  - imageio=2.37.0
  - ipykernel=6.29
  - ipython=8.30
  - jupyter=1.1
  - matplotlib=3.10.0
  - numpy=1.26.4
  - python=3.12
  - scikit-learn=1.6
  - scipy=1.13
  - tifffile=2024.12.12
  - tomosipo=0.6.0
  - tqdm=4.66
  - tomopy=1.15


